services:

  api:
    container_name: authjs_api

    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    ports:
      - "3000:3000"

    env_file:
      - .env

    command: node dist/main

  redis:
    image: redis:7-alpine

    container_name: authjs_redis

    restart: always

    ports:
      - "6379:6379"
