services:

  api:
    container_name: authjs_api

    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "http://localhost:3000"
        ]

      interval: 30s

      timeout: 10s

      retries: 5

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - redis

    command: yarn start:prod

  redis:
    image: redis:7-alpine

    container_name: authjs_redis

    restart: always
